[package]
name = "web-novel-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "cookies"] }
scraper = "0.22"
fake-useragent = "0.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
